# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwertyuiop
      MYSQL_DATABASE: orderservice
    ports:
      - "3306:3306"
    # (this is just an example, not intended to be a production configuration)
